version: '3.8'

services:
  frontend:
    build: ./frontend/
    container_name: Frontend
    ports:
      - '80:5173'
    depends_on:
      - backend

  backend:
    build: ./backend/
    container_name: Backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo_data:
    driver: local

